configuration:
  browser: chrome
  webElementTimeout: 10
  defaultTimeout: 3
  url: http://146.59.32.4/index.php

user:
  name: Jan
  lastName: Kowalski
  eMail: jkowalski@example.com
  password: jkowalski123@

searchTestData:
  product: HUMMINGBIRD

categoriesTestData:
  categoryNumber: 3
  subCategoryNumber: 4
  clothesCategoryNumber: 2
  categoryFilter: ACCESSORIES
  priceFrom: 13
  priceTo: 15

basketTestData:
  categoryName: ART
  productName: THE BEST IS YET POSTER
  quantity: 3
  productsNumber: 10



