configuration:
  browser: edge
  webElementTimeout: 10
  defaultTimeout: 3
  url: http://146.59.32.4/index.php

user:
  name: Jan
  lastName: Kowalski
  eMail: jkowalski@example.com
  password: jkowalski123@
  address: Baker Street 23
  city: New York
  state: New York
  postCode: 12133

searchTestData:
  product: HUMMINGBIRD

categoriesTestData:
  categoryNumber: 3
  subCategoryNumber: 4
  clothesCategoryNumber: 2
  categoryFilter: ACCESSORIES
  priceFrom: 13
  priceTo: 15

basketTestData:
  categoryName: ART
  productName: THE BEST IS YET POSTER
  quantity: 3
  productsNumberInOrderTest: 10
  productsNumberInRemovingTest: 2
  quantityRandom: 5
  indexOfElementToRemove: 1
  noItemsMessage: There are no more items in your cart
  quantityIfZeroProductsInCartText: (0)

checkoutTest:
  productNameInCheckoutTest: THE BEST IS YET POSTER
  secondAddress: Park Avenue 4
  secondCity: Texas
  secondState: California
  secondPostCode: 54214
  category: ORDER HISTORY AND DETAILS
  orderStatus: Awaiting check payment



